name: skylight-shopping-list
version: '1.0.0'
summary: Shopping list app with camera scanning and Skylight sync
description: |
  Skylight Shopping List is a modern Linux application that helps you manage
  your shopping lists with advanced features:
  
  - Camera scanning to detect pantry items
  - Barcode scanning with OpenFoodFacts integration  
  - Manual photo upload from your computer
  - Sync with Skylight Calendar API
  - Smart pantry management
  - Nutrition information tracking
  
  Built with GTK4 and libadwaita for a native GNOME experience.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  skylight-shopping-list:
    command: usr/bin/skylight-shopping-list
    extensions: [gnome]
    plugs:
      - home
      - network
      - camera
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages

parts:
  skylight-shopping-list:
    plugin: meson
    source: ../..
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - meson
      - ninja-build
      - python3-dev
      - libgtk-4-dev
      - libadwaita-1-dev
      - gobject-introspection
      - libgirepository1.0-dev
    stage-packages:
      - python3
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libgtk-4-1
      - libadwaita-1-0
    override-build: |
      craftctl default
      
      # Install Python dependencies
      python3 -m pip install --prefix=$CRAFT_PART_INSTALL/usr \
        requests \
        Pillow \
        numpy \
        opencv-python-headless \
        pyzbar
  
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv/archive/4.8.1.tar.gz
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_LIST=core,imgproc,imgcodecs,videoio,python3
      - -DBUILD_opencv_apps=OFF
      - -DBUILD_TESTS=OFF
      - -DBUILD_PERF_TESTS=OFF
      - -DBUILD_EXAMPLES=OFF
      - -DPYTHON3_EXECUTABLE=/usr/bin/python3
    build-packages:
      - cmake
      - g++
      - python3-dev
      - python3-numpy
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libatlas-base-dev
      - gfortran
    stage-packages:
      - libavcodec58
      - libavformat58
      - libswscale5
      - libv4l-0
      - libjpeg8
      - libpng16-16
  
  zbar:
    plugin: autotools
    source: https://github.com/mchehab/zbar.git
    source-tag: '0.23.92'
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-qt
      - --without-gtk
      - --without-x
      - --disable-video
      - --enable-codes=ean,code128,code39,qrcode
    build-packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
    stage-packages:
      - libzbar0

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0
